## 1. import

In [1]:
import numpy as np

## 2. 넘파이 배열 객체 array

In [4]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
list_data=[[1.5, -0.1, 3], [0, -3, 6.5]]
list_data+list_data

[[1.5, -0.1, 3], [0, -3, 6.5], [1.5, -0.1, 3], [0, -3, 6.5]]

In [9]:
list_data*10

[[1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5]]

## 3. 넘파이 배열 생성하기

In [4]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1,np.float32)
arr1

array([6. , 7.5, 8. , 0. , 1. ], dtype=float32)

In [18]:
arr2=np.array((1, 2, 3, 4))
arr2

array([1, 2, 3, 4])

In [19]:
arr1.ndim

1

In [21]:
arr1.shape

(5,)

In [22]:
arr1.size

5

In [23]:
arr1.dtype

dtype('float32')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2,np.int32)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2.shape, arr2.size

((2, 4), 8)

In [28]:
data3 = [[[1, 2, 3, 4], [5, 6, 7, 8]],[[9, 10, 11, 12], [13, 14, 15, 16]]]
arr3 = np.array(data3,np.int32)
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [29]:
arr3.shape, arr3.size

((2, 2, 4), 16)

## 4. 효율성 확인

In [30]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

795 µs ± 8.44 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
36.8 ms ± 375 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 5. 다른 방법으로 생성하기

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.empty((2, 3, 2))

array([[[9.2860e-312, 2.4703e-322],
        [0.0000e+000, 0.0000e+000],
        [1.0398e-312, 3.7623e+174]],

       [[6.2051e-091, 4.2550e+174],
        [9.9953e-048, 1.3940e+165],
        [3.9991e+252, 2.2728e+184]]])

In [28]:
np.full((2,3,2),2)

array([[[2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2]]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## 6. array의 자료형

In [31]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [32]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr.dtype

dtype('int32')

In [56]:
float_arr = arr.astype(np.float64)

In [57]:
float_arr

array([1., 2., 3., 4., 5.])

In [58]:
float_arr.dtype

dtype('float64')

In [63]:
arr=np.array([1+2j,3+4j],dtype=np.complex64)

In [64]:
arr

array([1.+2.j, 3.+4.j], dtype=complex64)

In [60]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [61]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

## 7. astype의 활용

In [37]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(np.float32)

array([ 1.25, -9.6 , 42.  ], dtype=float32)

In [41]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 8. 넘파이 배열의 산술 연산

### 원소별 개산, 브로드캐스팅

In [67]:
arr0=np.array([[1,2,3],[4,5,6]])

In [70]:
arr0+np.array(3)

array([[4, 5, 6],
       [7, 8, 9]])

In [71]:
arr0+np.array([1,2,3])

array([[2, 4, 6],
       [5, 7, 9]])

In [72]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [74]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [76]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [77]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## 9. 색인과 슬라이싱 기초

In [42]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### 넘파이 배열의 슬라이스는 뷰 (view) 이다.

In [44]:
list_a=list(range(10))
list_slice=list_a[5:8]
list_slice=[12,12,12]
list_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[:]=12   
arr_slice

array([12, 12, 12])

In [48]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## 10. 다차원 배열 색인과 슬라이싱

In [52]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0][1]

2

In [53]:
arr2d[0,1]

2

In [15]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 11. 다차원 슬라이싱

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [56]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr2d[:][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])